#ifndef _HECKT_VERSION_H_
#define _HECKT_VERSION_H_

#define HECKT_VERSION "v.1.0.0"
#define HECKT_RELEASE_DATE "2026.10.01"

#define HECKT_PIN_DUT 4
#define HECKT_PIN_RELAY 6
#define HECKT_PIN_BUTTON 2

#define HECKT_DUT_CAPACITANCE_LEVEL HIGH
#define HECKT_CAP_CALIBRATION_FARAD 1.5e-9f

#define HECKT_TIME_FREQ_GATE_MS 1000
#define HECKT_TIME_RELAY_SETTLE_MS 500
#define HECKT_TIME_RELAY_SAMPLE_MS 2000
#define HECKT_TIME_CALIB_RESET_HOLD_MS 1000

#define HECKT_EEPROM_ADDR_CALIB_FLAG 0
#define HECKT_EEPROM_ADDR_EFF_F 1
#define HECKT_EEPROM_ADDR_EFF_C (HECKT_EEPROM_ADDR_EFF_F + sizeof(double))
#define HECKT_EEPROM_ADDR_EFF_L (HECKT_EEPROM_ADDR_EFF_C + sizeof(double))

#define HECKT_EEPROM_CALIB_FLAG_VALID   0xA5
#define HECKT_EEPROM_CALIB_FLAG_INVALID 0x00

#endif
