#ifndef _HECKT_VERSION_H_
#define _HECKT_VERSION_H_

#define HECKT_VERSION "v.0.1.0"
#define HECKT_RELEASE_DATE "2026.09.30"

#define HECKT_PIN_DUT 4
#define HECKT_PIN_RELAY 6
#define HECKT_PIN_BUTTON 2

#define HECKT_DUT_CAPACITANCE_LEVEL HIGH
#define HECKT_CAP_CALIBRATION_FARAD 1.5e-9f

#define HECKT_TIME_FREQ_GATE_MS 1000
#define HECKT_TIME_RELAY_SETTLE_MS 500
#define HECKT_TIME_RELAY_SAMPLE_MS 2000

#endif
